### ISSUE TITLE
Estrutura de Packages SpringBoot

### ISSUE THREAD

**Issue by jonaellemos** [MarlonJerold/aprendendoensinando-backend#5]
Com o intuito de melhorar as práticas do projeto e aprender ensinando, segue um modelo que acho que atenda a maioria das aplicações no quesito de estrutura de apis spring. 

Caso achem também necessário, me ponho à disposição para ajudar no que for possível. 
Obrigado pela oportunidade de contribuir.

**Comment by MarlonJerold** [comment]
É nóssss, obrigado pela contribuição
